server:
  port: 9002

spring:
  application:
    name: message-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: jurisai
    password: jurisai
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/message-service-changelog.xml
    default-schema: message_service
  kafka:
    bootstrap-servers: 26.59.67.70:9092
    consumer:
      group-id: myListener
logging:
  file:
    name: ${spring.application.name}.log
    path: ./logs

snowflake:
  worker-id: 3
  datacenter-id: 1

kafka:
  topic:
    answers_topic: answers_topic